--drop table items,users,requests,bookings,comments;
create TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  is_available BOOLEAN,
  owner_id BIGINT,
  request_id BIGINT
  --CONSTRAINT pk_item PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL
  --CONSTRAINT pk_user PRIMARY KEY (id),
  --CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
  --FOREIGN KEY (id) REFERENCES items(owner_id)
);
create TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(255) NOT NULL,
  requestor_id BIGINT NOT NULL
  --FOREIGN KEY (id) REFERENCES items(request_id)
);
create TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  itme_id BIGINT NOT NULL,
  booker_id  BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL
  --FOREIGN KEY (id) REFERENCES items(request_id)
);
create TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(255) NOT NULL,
   itme_id BIGINT NOT NULL,
   author_id BIGINT NOT NULL
  --FOREIGN KEY (id) REFERENCES items(request_id)
);