--drop table items,users,requests,bookings,comments;
create TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  user_email VARCHAR(512) NOT NULL UNIQUE,
  CONSTRAINT pk_user PRIMARY KEY (user_id)
);
create table if not exists requests (
  request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  request_description VARCHAR(255) NOT NULL,
  requestor_id BIGINT NOT NULL,
  request_created TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT pk_request PRIMARY KEY (request_id)
);
create table if not exists items (
  item_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
  item_name VARCHAR(255) NOT NULL,
  item_description VARCHAR(512) NOT NULL,
  is_available BOOLEAN,
  owner_id BIGINT REFERENCES users(user_id),
  request_id BIGINT REFERENCES requests(request_id),
  CONSTRAINT pk_item PRIMARY KEY (item_id)
);
create table if not exists bookings (
  booking_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE,
  end_date TIMESTAMP WITHOUT TIME ZONE,
  itme_id BIGINT NOT NULL,
  booker_id  BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL,
  CONSTRAINT pk_bookings PRIMARY KEY (booking_id)
);
create table if not exists comments (
  comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(255) NOT NULL,
   itme_id BIGINT NOT NULL,
   author_id BIGINT NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (comment_id)
);